# Venture Funding with Deep Learning

You work as a risk management associate at Alphabet Soup, a venture capital firm. Alphabet Soup’s business team receives many funding applications from startups every day. This team has asked you to help them create a model that predicts whether applicants will be successful if funded by Alphabet Soup.

The business team has given you a CSV containing more than 34,000 organizations that have received funding from Alphabet Soup over the years. With your knowledge of machine learning and neural networks, you decide to use the features in the provided dataset to create a binary classifier model that will predict whether an applicant will become a successful business. The CSV file contains a variety of information about these businesses, including whether or not they ultimately became successful.

## Instructions:

The steps for this challenge are broken out into the following sections:

* Prepare the data for use on a neural network model.

* Compile and evaluate a binary classification model using a neural network.

* Optimize the neural network model.

### Prepare the Data for Use on a Neural Network Model 

Using your knowledge of Pandas and scikit-learn’s `StandardScaler()`, preprocess the dataset so that you can use it to compile and evaluate the neural network model later.

Open the starter code file, and complete the following data preparation steps:

1. Read the `applicants_data.csv` file into a Pandas DataFrame. Review the DataFrame, looking for categorical variables that will need to be encoded, as well as columns that could eventually define your features and target variables.   

2. Drop the “EIN” (Employer Identification Number) and “NAME” columns from the DataFrame, because they are not relevant to the binary classification model.
 
3. Encode the dataset’s categorical variables using `OneHotEncoder`, and then place the encoded variables into a new DataFrame.

4. Add the original DataFrame’s numerical variables to the DataFrame containing the encoded variables.

> **Note** To complete this step, you will employ the Pandas `concat()` function that was introduced earlier in this course. 

5. Using the preprocessed data, create the features (`X`) and target (`y`) datasets. The target dataset should be defined by the preprocessed DataFrame column “IS_SUCCESSFUL”. The remaining columns should define the features dataset. 

6. Split the features and target sets into training and testing datasets.

7. Use scikit-learn's `StandardScaler` to scale the features data.

### Compile and Evaluate a Binary Classification Model Using a Neural Network

Use your knowledge of TensorFlow to design a binary classification deep neural network model. This model should use the dataset’s features to predict whether an Alphabet Soup&ndash;funded startup will be successful based on the features in the dataset. Consider the number of inputs before determining the number of layers that your model will contain or the number of neurons on each layer. Then, compile and fit your model. Finally, evaluate your binary classification model to calculate the model’s loss and accuracy. 
 
To do so, complete the following steps:

1. Create a deep neural network by assigning the number of input features, the number of layers, and the number of neurons on each layer using Tensorflow’s Keras.

> **Hint** You can start with a two-layer deep neural network model that uses the `relu` activation function for both layers.

2. Compile and fit the model using the `binary_crossentropy` loss function, the `adam` optimizer, and the `accuracy` evaluation metric.

> **Hint** When fitting the model, start with a small number of epochs, such as 20, 50, or 100.

3. Evaluate the model using the test data to determine the model’s loss and accuracy.

4. Save and export your model to an HDF5 file, and name the file `AlphabetSoup.h5`. 

### Optimize the Neural Network Model

Using your knowledge of TensorFlow and Keras, optimize your model to improve the model's accuracy. Even if you do not successfully achieve a better accuracy, you'll need to demonstrate at least two attempts to optimize the model. You can include these attempts in your existing notebook. Or, you can make copies of the starter notebook in the same folder, rename them, and code each model optimization in a new notebook. 

> **Note** You will not lose points if your model does not achieve a high accuracy, as long as you make at least two attempts to optimize the model.

To do so, complete the following steps:

1. Define at least three new deep neural network models (the original plus 2 optimization attempts). With each, try to improve on your first model’s predictive accuracy.

> **Rewind** Recall that perfect accuracy has a value of 1, so accuracy improves as its value moves closer to 1. To optimize your model for a predictive accuracy as close to 1 as possible, you can use any or all of the following techniques:
>
> * Adjust the input data by dropping different features columns to ensure that no variables or outliers confuse the model.
>
> * Add more neurons (nodes) to a hidden layer.
>
> * Add more hidden layers.
>
> * Use different activation functions for the hidden layers.
>
> * Add to or reduce the number of epochs in the training regimen.

2. After finishing your models, display the accuracy scores achieved by each model, and compare the results.

3. Save each of your models as an HDF5 file.

In [1]:
# Imports
import pandas as pd
from pathlib import Path
import tensorflow as tf
from tensorflow.keras.layers import Dense
from tensorflow.keras.models import Sequential
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler,OneHotEncoder

---

## Prepare the data to be used on a neural network model

### Step 1: Read the `applicants_data.csv` file into a Pandas DataFrame. Review the DataFrame, looking for categorical variables that will need to be encoded, as well as columns that could eventually define your features and target variables.

In [2]:
# Read the applicants_data.csv file from the Resources folder into a Pandas DataFrame
data = Path("../Starter_Code/Resources/applicants_data.csv")
applicant_data_df = pd.read_csv(data)

# Review the DataFrame
applicant_data_df.head()

,EIN,NAME,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,10520599,BLUE KNIGHTS MOTORCYCLE CLUB,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,10531628,AMERICAN CHESAPEAKE CLUB CHARITABLE TR,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,10547893,ST CLOUD PROFESSIONAL FIREFIGHTERS,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,10553066,SOUTHSIDE ATHLETIC ASSOCIATION,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,10556103,GENETIC RESEARCH INSTITUTE OF THE DESERT,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1

In [3]:
# Review the data types associated with the columns
applicant_data_df.dtypes

EIN                        int64
NAME                      object
APPLICATION_TYPE          object
AFFILIATION               object
CLASSIFICATION            object
USE_CASE                  object
ORGANIZATION              object
STATUS                     int64
INCOME_AMT                object
SPECIAL_CONSIDERATIONS    object
ASK_AMT                    int64
IS_SUCCESSFUL              int64
dtype: object

### Step 2: Drop the “EIN” (Employer Identification Number) and “NAME” columns from the DataFrame, because they are not relevant to the binary classification model.

In [4]:
# Drop the 'EIN' and 'NAME' columns from the DataFrame
applicant_data_df = applicant_data_df.drop(['EIN', 'NAME'], axis=1)

# Review the DataFrame
applicant_data_df.head()

,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1

In [5]:
applicant_data_df.dtypes

APPLICATION_TYPE          object
AFFILIATION               object
CLASSIFICATION            object
USE_CASE                  object
ORGANIZATION              object
STATUS                     int64
INCOME_AMT                object
SPECIAL_CONSIDERATIONS    object
ASK_AMT                    int64
IS_SUCCESSFUL              int64
dtype: object

### Step 3: Encode the dataset’s categorical variables using `OneHotEncoder`, and then place the encoded variables into a new DataFrame.

In [6]:
# Create a list of categorical variables 

categorical_variables = ['APPLICATION_TYPE' ,
                   'AFFILIATION' ,
                   'CLASSIFICATION' ,
                   'USE_CASE' ,
                   'ORGANIZATION',
                   'INCOME_AMT'
                   'SPECIAL_CONSIDERATIONS'] 

# Display the categorical variables list
list(applicant_data_df.dtypes[applicant_data_df.dtypes == "object"].index)

['APPLICATION_TYPE',
 'AFFILIATION',
 'CLASSIFICATION',
 'USE_CASE',
 'ORGANIZATION',
 'INCOME_AMT',
 'SPECIAL_CONSIDERATIONS']

In [7]:
# Create a OneHotEncoder instance
enc = OneHotEncoder(sparse=False)

In [8]:
# Create a list of the columns with categorical variables
categorical_variables = ["APPLICATION_TYPE", "AFFILIATION", "CLASSIFICATION", "USE_CASE", "ORGANIZATION", "INCOME_AMT", "SPECIAL_CONSIDERATIONS"]

In [9]:
# Encode the categorcal variables using OneHotEncoder
encoded_data = enc.fit_transform(applicant_data_df[categorical_variables])

In [10]:
# Create a DataFrame with the encoded variables
encoded_df = pd.DataFrame(
    encoded_data,
    columns = enc.get_feature_names(categorical_variables)
)
# Review the DataFrame
encoded_df.head()

C:\Users\alexs\anaconda3\envs\dev\lib\site-packages\sklearn\utils\deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)

,APPLICATION_TYPE_T10,APPLICATION_TYPE_T12,APPLICATION_TYPE_T13,APPLICATION_TYPE_T14,APPLICATION_TYPE_T15,APPLICATION_TYPE_T17,APPLICATION_TYPE_T19,APPLICATION_TYPE_T2,APPLICATION_TYPE_T25,APPLICATION_TYPE_T29,...,INCOME_AMT_1-9999,INCOME_AMT_10000-24999,INCOME_AMT_100000-499999,INCOME_AMT_10M-50M,INCOME_AMT_1M-5M,INCOME_AMT_25000-99999,INCOME_AMT_50M+,INCOME_AMT_5M-10M,SPECIAL_CONSIDERATIONS_N,SPECIAL_CONSIDERATIONS_Y
0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0

### Step 4: Add the original DataFrame’s numerical variables to the DataFrame containing the encoded variables.

> **Note** To complete this step, you will employ the Pandas `concat()` function that was introduced earlier in this course.

In [11]:
# Add the numerical variables from the original DataFrame to the one-hot encoding DataFrame
encoded_df = pd.concat(
    [
        applicant_data_df[["STATUS", "ASK_AMT", "IS_SUCCESSFUL"]],
        encoded_df
    ],
    axis=1
)
# Review the Dataframe
encoded_df.head()

,STATUS,ASK_AMT,IS_SUCCESSFUL,APPLICATION_TYPE_T10,APPLICATION_TYPE_T12,APPLICATION_TYPE_T13,APPLICATION_TYPE_T14,APPLICATION_TYPE_T15,APPLICATION_TYPE_T17,APPLICATION_TYPE_T19,...,INCOME_AMT_1-9999,INCOME_AMT_10000-24999,INCOME_AMT_100000-499999,INCOME_AMT_10M-50M,INCOME_AMT_1M-5M,INCOME_AMT_25000-99999,INCOME_AMT_50M+,INCOME_AMT_5M-10M,SPECIAL_CONSIDERATIONS_N,SPECIAL_CONSIDERATIONS_Y
0,1,5000,1,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
1,1,108590,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
2,1,5000,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
3,1,6692,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
4,1,142590,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0

### Step 5: Using the preprocessed data, create the features (`X`) and target (`y`) datasets. The target dataset should be defined by the preprocessed DataFrame column “IS_SUCCESSFUL”. The remaining columns should define the features dataset.

In [12]:
encoded_df.shape

(34299, 117)

In [13]:
# Define the target set y using the IS_SUCCESSFUL column
y = encoded_df['IS_SUCCESSFUL']

# Display a sample of y
y

0        1
1        1
2        0
3        1
4        1
        ..
34294    0
34295    0
34296    0
34297    1
34298    0
Name: IS_SUCCESSFUL, Length: 34299, dtype: int64

In [14]:
# Define features set X by selecting all columns but IS_SUCCESSFUL
X = encoded_df.drop(columns=["IS_SUCCESSFUL"])

In [15]:
# Review the features DataFrame
X

,STATUS,ASK_AMT,APPLICATION_TYPE_T10,APPLICATION_TYPE_T12,APPLICATION_TYPE_T13,APPLICATION_TYPE_T14,APPLICATION_TYPE_T15,APPLICATION_TYPE_T17,APPLICATION_TYPE_T19,APPLICATION_TYPE_T2,...,INCOME_AMT_1-9999,INCOME_AMT_10000-24999,INCOME_AMT_100000-499999,INCOME_AMT_10M-50M,INCOME_AMT_1M-5M,INCOME_AMT_25000-99999,INCOME_AMT_50M+,INCOME_AMT_5M-10M,SPECIAL_CONSIDERATIONS_N,SPECIAL_CONSIDERATIONS_Y
0,1,5000,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
1,1,108590,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
2,1,5000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
3,1,6692,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
4,1,142590,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
34294,1,5000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
34295,1,5000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
34296,1,5000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
34297,1,5000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
34298,1,36500179,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0

### Step 6: Split the features and target sets into training and testing datasets.

In [16]:
# Split the preprocessed data into a training and testing dataset
# Assign the function a random_state equal to 1
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=1)

### Step 7: Use scikit-learn's `StandardScaler` to scale the features data.

In [17]:
# Create a StandardScaler instance
scaler = StandardScaler()

In [18]:
# Fit the scaler to the features training dataset
x_scaler = scaler.fit(X_train)

In [19]:
# Fit the scaler to the features training dataset
X_train_scaled = x_scaler.transform(X_train)
X_test_scaled = x_scaler.transform(X_test)

In [58]:
X_train_scaled.shape

(25724, 116)

In [60]:
y_train.shape

(25724,)

---

## Compile and Evaluate a Binary Classification Model Using a Neural Network

### Step 1: Create a deep neural network by assigning the number of input features, the number of layers, and the number of neurons on each layer using Tensorflow’s Keras.

> **Hint** You can start with a two-layer deep neural network model that uses the `relu` activation function for both layers.

In [20]:
# Define the the number of inputs (features) to the model
number_input_features = 116
# could also use this code: number_input_features = len(X_train.iloc[0])

# Review the number of features
number_input_features

116

In [21]:
# Define the number of neurons in the output layer
number_output_neurons = 8

In [22]:
# Define the number of hidden nodes for the first hidden layer
hidden_nodes_layer1 =  4

# Review the number hidden nodes in the first layer
hidden_nodes_layer1

4

In [23]:
# Define the number of hidden nodes for the second hidden layer
hidden_nodes_layer2 =  4

# Review the number hidden nodes in the second layer
hidden_nodes_layer2

4

In [24]:
# Create the Sequential model instance
nn = Sequential()

In [25]:
# Add the first hidden layer
nn.add(Dense(units=hidden_nodes_layer1, activation="relu", input_dim=number_input_features))

In [26]:
# Add the second hidden layer
nn.add(Dense(units=hidden_nodes_layer2, activation="relu", input_dim=number_input_features))

In [27]:
# Add the output layer to the model specifying the number of output neurons and activation function
number_classes = 1

nn.add(Dense(units=number_classes, activation="sigmoid"))

In [28]:
# Display the Sequential model summary
nn.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense (Dense)               (None, 4)                 468

 dense_1 (Dense)             (None, 4)                 20

 dense_2 (Dense)             (None, 1)                 5

=================================================================
Total params: 493
Trainable params: 493
Non-trainable params: 0
_________________________________________________________________

### Step 2: Compile and fit the model using the `binary_crossentropy` loss function, the `adam` optimizer, and the `accuracy` evaluation metric.

In [29]:
# Compile the Sequential model
nn.compile(loss="binary_crossentropy", optimizer="adam", metrics=["accuracy"])

In [30]:
# Fit the model using 50 epochs and the training data
venture_model = nn.fit(X_train_scaled, y_train, epochs=50)

Epoch 1/50
804/804 [==============================] - 2s 2ms/step - loss: 0.6133 - accuracy: 0.6819
Epoch 2/50
804/804 [==============================] - 1s 1ms/step - loss: 0.5678 - accuracy: 0.7170
Epoch 3/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5601 - accuracy: 0.7220
Epoch 4/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5572 - accuracy: 0.7236
Epoch 5/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5558 - accuracy: 0.7267
Epoch 6/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5552 - accuracy: 0.7275
Epoch 7/50
804/804 [==============================] - 2s 3ms/step - loss: 0.5542 - accuracy: 0.7266
Epoch 8/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5537 - accuracy: 0.7270
Epoch 9/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5533 - accuracy: 0.7276
Epoch 10/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5526 - accuracy: 0.7282
Epoch 11/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5525 - accuracy: 0.7281
Epoch 12/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5522 - accuracy: 0.7280
Epoch 13/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5518 - accuracy: 0.7277
Epoch 14/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5514 - accuracy: 0.7283
Epoch 15/50
804/804 [==============================] - 2s 3ms/step - loss: 0.5512 - accuracy: 0.7285
Epoch 16/50
804/804 [==============================] - 3s 3ms/step - loss: 0.5509 - accuracy: 0.7284
Epoch 17/50
804/804 [==============================] - 2s 3ms/step - loss: 0.5508 - accuracy: 0.7281
Epoch 18/50
804/804 [==============================] - 2s 3ms/step - loss: 0.5504 - accuracy: 0.7285
Epoch 19/50
804/804 [==============================] - 3s 3ms/step - loss: 0.5504 - accuracy: 0.7283
Epoch 20/50
804/804 [==============================] - 2s 3ms/step - loss: 0.5501 - accuracy: 0.7294
Epoch 21/50
804/804 [==============================] - 2s 3ms/step - loss: 0.5500 - accuracy: 0.7289
Epoch 22/50
804/804 [==============================] - 2s 3ms/step - loss: 0.5499 - accuracy: 0.7294
Epoch 23/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5500 - accuracy: 0.7292
Epoch 24/50
804/804 [==============================] - 2s 3ms/step - loss: 0.5497 - accuracy: 0.7285
Epoch 25/50
804/804 [==============================] - 2s 3ms/step - loss: 0.5496 - accuracy: 0.7288
Epoch 26/50
804/804 [==============================] - 2s 3ms/step - loss: 0.5495 - accuracy: 0.7281
Epoch 27/50
804/804 [==============================] - 2s 3ms/step - loss: 0.5496 - accuracy: 0.7291
Epoch 28/50
804/804 [==============================] - 2s 3ms/step - loss: 0.5493 - accuracy: 0.7288
Epoch 29/50
804/804 [==============================] - 2s 3ms/step - loss: 0.5491 - accuracy: 0.7283
Epoch 30/50
804/804 [==============================] - 2s 3ms/step - loss: 0.5493 - accuracy: 0.7278
Epoch 31/50
804/804 [==============================] - 2s 3ms/step - loss: 0.5491 - accuracy: 0.7287
Epoch 32/50
804/804 [==============================] - 2s 3ms/step - loss: 0.5490 - accuracy: 0.7284
Epoch 33/50
804/804 [==============================] - 2s 3ms/step - loss: 0.5489 - accuracy: 0.7281
Epoch 34/50
804/804 [==============================] - 2s 3ms/step - loss: 0.5488 - accuracy: 0.7282
Epoch 35/50
804/804 [==============================] - 2s 3ms/step - loss: 0.5483 - accuracy: 0.7295
Epoch 36/50
804/804 [==============================] - 3s 3ms/step - loss: 0.5487 - accuracy: 0.7290
Epoch 37/50
804/804 [==============================] - 4s 5ms/step - loss: 0.5487 - accuracy: 0.7282
Epoch 38/50
804/804 [==============================] - 3s 4ms/step - loss: 0.5484 - accuracy: 0.7292
Epoch 39/50
804/804 [==============================] - 3s 3ms/step - loss: 0.5485 - accuracy: 0.7279
Epoch 40/50
804/804 [==============================] - 3s 4ms/step - loss: 0.5482 - accuracy: 0.7291
Epoch 41/50
804/804 [==============================] - 3s 3ms/step - loss: 0.5487 - accuracy: 0.7287
Epoch 42/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5484 - accuracy: 0.7284
Epoch 43/50
804/804 [==============================] - 2s 3ms/step - loss: 0.5483 - accuracy: 0.7289
Epoch 44/50
804/804 [==============================] - 2s 3ms/step - loss: 0.5483 - accuracy: 0.7284
Epoch 45/50
804/804 [==============================] - 2s 3ms/step - loss: 0.5484 - accuracy: 0.7287
Epoch 46/50
804/804 [==============================] - 2s 3ms/step - loss: 0.5479 - accuracy: 0.7289
Epoch 47/50
804/804 [==============================] - 3s 3ms/step - loss: 0.5480 - accuracy: 0.7285
Epoch 48/50
804/804 [==============================] - 2s 3ms/step - loss: 0.5477 - accuracy: 0.7286
Epoch 49/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5479 - accuracy: 0.7295
Epoch 50/50
804/804 [==============================] - 2s 3ms/step - loss: 0.5475 - accuracy: 0.7276

### Step 3: Evaluate the model using the test data to determine the model’s loss and accuracy.

In [31]:
# Evaluate the model loss and accuracy metrics using the evaluate method and the test data
model_loss, model_accuracy = nn.evaluate(
    X_test_scaled, y_test, verbose=2
)
# Display the model loss and accuracy results
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

268/268 - 1s - loss: 0.5584 - accuracy: 0.7236 - 677ms/epoch - 3ms/step
Loss: 0.5584390163421631, Accuracy: 0.7236151695251465

### Step 4: Save and export your model to an HDF5 file, and name the file `AlphabetSoup.h5`.

In [32]:
# Set the model's file path
file_path = Path('../Starter_Code/AlphabetSoup.h5')
nn.save(file_path)

In [33]:
# Export your model to a HDF5 file
nn_imported = tf.keras.models.load_model(file_path)

---

## Optimize the neural network model

### Step 1: Define at least three new deep neural network models (resulting in the original plus 3 optimization attempts). With each, try to improve on your first model’s predictive accuracy.

> **Rewind** Recall that perfect accuracy has a value of 1, so accuracy improves as its value moves closer to 1. To optimize your model for a predictive accuracy as close to 1 as possible, you can use any or all of the following techniques:
>
> * Adjust the input data by dropping different features columns to ensure that no variables or outliers confuse the model.
>
> * Add more neurons (nodes) to a hidden layer.
>
> * Add more hidden layers.
>
> * Use different activation functions for the hidden layers.
>
> * Add to or reduce the number of epochs in the training regimen.

### Alternative Model 1

In [34]:
# Define the the number of inputs (features) to the model
number_input_features = len(X_train.iloc[0])

# Review the number of features
number_input_features

116

In [35]:
# Define the number of neurons in the output layer
number_output_neurons_A1 = 8

In [36]:
# Define the number of hidden nodes for the first hidden layer
hidden_nodes_layer1_A1 = 6

# Review the number of hidden nodes in the first layer
hidden_nodes_layer1_A1

6

In [37]:
# Create the Sequential model instance
nn_A1 = Sequential()

In [38]:
# First hidden layer
nn_A1.add(Dense(units=hidden_nodes_layer1_A1, activation="sigmoid", input_dim=number_input_features))

In [61]:
# Output layer
number_classes_A1 = 1

nn_A1.add(Dense(units=number_classes_A1, activation="sigmoid"))

In [62]:
# Check the structure of the model
nn_A1.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense_3 (Dense)             (None, 6)                 702

 dense_4 (Dense)             (None, 3)                 21

 dense_5 (Dense)             (None, 6)                 24

 dense_6 (Dense)             (None, 6)                 42

 dense_9 (Dense)             (None, 1)                 7

=================================================================
Total params: 796
Trainable params: 796
Non-trainable params: 0
_________________________________________________________________

In [63]:
# Compile the Sequential model
nn_A1.compile(loss='binary_crossentropy', optimizer='nadam', metrics=['accuracy'])

In [64]:
# Fit the model using 50 epochs and the training data
fit_model_A1 = nn_A1.fit(X_train_scaled, y_train, epochs = 100)

Epoch 1/100
804/804 [==============================] - 4s 2ms/step - loss: 0.6788 - accuracy: 0.5707
Epoch 2/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5981 - accuracy: 0.7254
Epoch 3/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5776 - accuracy: 0.7275
Epoch 4/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5757 - accuracy: 0.7285
Epoch 5/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5750 - accuracy: 0.7281
Epoch 6/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5744 - accuracy: 0.7285
Epoch 7/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5740 - accuracy: 0.7296
Epoch 8/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5736 - accuracy: 0.7297
Epoch 9/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5732 - accuracy: 0.7301
Epoch 10/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5726 - accuracy: 0.7301
Epoch 11/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5721 - accuracy: 0.7303
Epoch 12/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5717 - accuracy: 0.7309
Epoch 13/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5714 - accuracy: 0.7318
Epoch 14/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5709 - accuracy: 0.7312
Epoch 15/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5706 - accuracy: 0.7311
Epoch 16/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5701 - accuracy: 0.7313
Epoch 17/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5698 - accuracy: 0.7311
Epoch 18/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5693 - accuracy: 0.7319
Epoch 19/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5692 - accuracy: 0.7322
Epoch 20/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5687 - accuracy: 0.7322
Epoch 21/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5685 - accuracy: 0.7324
Epoch 22/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5682 - accuracy: 0.7324
Epoch 23/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5679 - accuracy: 0.7322
Epoch 24/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5678 - accuracy: 0.7323
Epoch 25/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5676 - accuracy: 0.7327
Epoch 26/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5672 - accuracy: 0.7327
Epoch 27/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5665 - accuracy: 0.7332
Epoch 28/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5660 - accuracy: 0.7324
Epoch 29/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5652 - accuracy: 0.7321
Epoch 30/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5638 - accuracy: 0.7339
Epoch 31/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5619 - accuracy: 0.7323
Epoch 32/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5591 - accuracy: 0.7323
Epoch 33/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5570 - accuracy: 0.7323
Epoch 34/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5554 - accuracy: 0.7330
Epoch 35/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5543 - accuracy: 0.7329
Epoch 36/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5535 - accuracy: 0.7325
Epoch 37/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5530 - accuracy: 0.7328
Epoch 38/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5524 - accuracy: 0.7338
Epoch 39/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5520 - accuracy: 0.7334
Epoch 40/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5517 - accuracy: 0.7334
Epoch 41/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5512 - accuracy: 0.7338
Epoch 42/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5510 - accuracy: 0.7340
Epoch 43/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5507 - accuracy: 0.7339
Epoch 44/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5505 - accuracy: 0.7338
Epoch 45/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5501 - accuracy: 0.7333
Epoch 46/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5498 - accuracy: 0.7343
Epoch 47/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5495 - accuracy: 0.7341
Epoch 48/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5491 - accuracy: 0.7339
Epoch 49/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5488 - accuracy: 0.7338
Epoch 50/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5485 - accuracy: 0.7340
Epoch 51/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5484 - accuracy: 0.7336
Epoch 52/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5481 - accuracy: 0.7344
Epoch 53/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5478 - accuracy: 0.7343
Epoch 54/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5477 - accuracy: 0.7344
Epoch 55/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5476 - accuracy: 0.7344
Epoch 56/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5474 - accuracy: 0.7341
Epoch 57/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5471 - accuracy: 0.7349
Epoch 58/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5470 - accuracy: 0.7350
Epoch 59/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5467 - accuracy: 0.7345
Epoch 60/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5466 - accuracy: 0.7351
Epoch 61/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5465 - accuracy: 0.7350
Epoch 62/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5461 - accuracy: 0.7348
Epoch 63/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5460 - accuracy: 0.7342
Epoch 64/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5456 - accuracy: 0.7343
Epoch 65/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5453 - accuracy: 0.7348
Epoch 66/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5453 - accuracy: 0.7356
Epoch 67/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5451 - accuracy: 0.7353
Epoch 68/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5451 - accuracy: 0.7349
Epoch 69/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5450 - accuracy: 0.7352
Epoch 70/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5445 - accuracy: 0.7350
Epoch 71/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5445 - accuracy: 0.7351
Epoch 72/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5444 - accuracy: 0.7341
Epoch 73/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5446 - accuracy: 0.7348
Epoch 74/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5442 - accuracy: 0.7341
Epoch 75/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5443 - accuracy: 0.7345
Epoch 76/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5440 - accuracy: 0.7347
Epoch 77/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5440 - accuracy: 0.7339
Epoch 78/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5437 - accuracy: 0.7354
Epoch 79/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5438 - accuracy: 0.7352
Epoch 80/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5435 - accuracy: 0.7352
Epoch 81/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5435 - accuracy: 0.7354
Epoch 82/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5435 - accuracy: 0.7351
Epoch 83/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5434 - accuracy: 0.7352
Epoch 84/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5432 - accuracy: 0.7350
Epoch 85/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5430 - accuracy: 0.7352
Epoch 86/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5428 - accuracy: 0.7339
Epoch 87/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5428 - accuracy: 0.7350
Epoch 88/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5427 - accuracy: 0.7353
Epoch 89/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5424 - accuracy: 0.7358
Epoch 90/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5425 - accuracy: 0.7360
Epoch 91/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5426 - accuracy: 0.7342
Epoch 92/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5424 - accuracy: 0.7354
Epoch 93/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5422 - accuracy: 0.7355
Epoch 94/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5422 - accuracy: 0.7355
Epoch 95/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5424 - accuracy: 0.7347
Epoch 96/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5421 - accuracy: 0.7352
Epoch 97/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5420 - accuracy: 0.7354
Epoch 98/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5420 - accuracy: 0.7349
Epoch 99/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5422 - accuracy: 0.7355
Epoch 100/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5421 - accuracy: 0.7357

#### Alternative Model 2

In [48]:
# Define the the number of inputs (features) to the model
number_input_features = len(X_train.iloc[0])

# Review the number of features
number_input_features

116

In [49]:
# Define the number of neurons in the output layer
number_output_neurons_A2 = 12

In [50]:
# Define the number of hidden nodes for the first hidden layer
hidden_nodes_layer1_A2 = 10

# Review the number of hidden nodes in the first layer
hidden_nodes_layer1_A2

10

In [51]:
# Create the Sequential model instance
nn_A2 = Sequential()

In [52]:
# First hidden layer
nn_A2.add(Dense(units=hidden_nodes_layer1_A2, activation="tanh", input_dim=number_input_features))

In [53]:
# Output layer
number_classes_A2 = 6
nn_A2.add(Dense(units=number_classes_A2, activation="tanh"))

In [54]:
# Check the structure of the model
nn_A2.summary()

Model: "sequential_2"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense_7 (Dense)             (None, 10)                1170

 dense_8 (Dense)             (None, 6)                 66

=================================================================
Total params: 1,236
Trainable params: 1,236
Non-trainable params: 0
_________________________________________________________________

In [55]:
# Compile the model
nn_A2.compile(loss='binary_crossentropy', optimizer='adagrad', metrics=['accuracy'])

In [56]:
# Fit the model
fit_model_A2 = nn_A2.fit(X_train_scaled, y_train, epochs = 100)

Epoch 1/100
804/804 [==============================] - 3s 2ms/step - loss: 4.8249 - accuracy: 0.1721
Epoch 2/100
804/804 [==============================] - 2s 2ms/step - loss: 4.7184 - accuracy: 0.2639
Epoch 3/100
804/804 [==============================] - 2s 2ms/step - loss: 4.6941 - accuracy: 0.2724
Epoch 4/100
804/804 [==============================] - 2s 2ms/step - loss: 4.6781 - accuracy: 0.2708
Epoch 5/100
804/804 [==============================] - 2s 2ms/step - loss: 4.6701 - accuracy: 0.2682
Epoch 6/100
804/804 [==============================] - 2s 2ms/step - loss: 4.6677 - accuracy: 0.2681
Epoch 7/100
804/804 [==============================] - 2s 2ms/step - loss: 4.6655 - accuracy: 0.2681
Epoch 8/100
804/804 [==============================] - 2s 2ms/step - loss: 4.6619 - accuracy: 0.2684
Epoch 9/100
804/804 [==============================] - 2s 2ms/step - loss: 4.6601 - accuracy: 0.2681
Epoch 10/100
804/804 [==============================] - 2s 2ms/step - loss: 4.6583 - accuracy: 0.2681
Epoch 11/100
804/804 [==============================] - 2s 2ms/step - loss: 4.6558 - accuracy: 0.2677
Epoch 12/100
804/804 [==============================] - 2s 2ms/step - loss: 4.6531 - accuracy: 0.2676
Epoch 13/100
804/804 [==============================] - 2s 2ms/step - loss: 4.6499 - accuracy: 0.2674
Epoch 14/100
804/804 [==============================] - 2s 2ms/step - loss: 4.6477 - accuracy: 0.2674
Epoch 15/100
804/804 [==============================] - 2s 2ms/step - loss: 4.6424 - accuracy: 0.2674
Epoch 16/100
804/804 [==============================] - 2s 2ms/step - loss: 4.6331 - accuracy: 0.2674
Epoch 17/100
804/804 [==============================] - 2s 2ms/step - loss: 4.6174 - accuracy: 0.2674
Epoch 18/100
804/804 [==============================] - 2s 2ms/step - loss: 4.6144 - accuracy: 0.2674
Epoch 19/100
804/804 [==============================] - 2s 2ms/step - loss: 4.6134 - accuracy: 0.2674
Epoch 20/100
804/804 [==============================] - 2s 2ms/step - loss: 4.6125 - accuracy: 0.2675
Epoch 21/100
804/804 [==============================] - 2s 2ms/step - loss: 4.6118 - accuracy: 0.2674
Epoch 22/100
804/804 [==============================] - 2s 2ms/step - loss: 4.6110 - accuracy: 0.2675
Epoch 23/100
804/804 [==============================] - 2s 2ms/step - loss: 4.6090 - accuracy: 0.2673
Epoch 24/100
804/804 [==============================] - 2s 2ms/step - loss: 4.6086 - accuracy: 0.2673
Epoch 25/100
804/804 [==============================] - 2s 2ms/step - loss: 4.6082 - accuracy: 0.2673
Epoch 26/100
804/804 [==============================] - 2s 2ms/step - loss: 4.6067 - accuracy: 0.2673
Epoch 27/100
804/804 [==============================] - 2s 2ms/step - loss: 4.6062 - accuracy: 0.2673
Epoch 28/100
804/804 [==============================] - 2s 2ms/step - loss: 4.6057 - accuracy: 0.2673
Epoch 29/100
804/804 [==============================] - 2s 2ms/step - loss: 4.6051 - accuracy: 0.2673
Epoch 30/100
804/804 [==============================] - 2s 2ms/step - loss: 4.6047 - accuracy: 0.2672
Epoch 31/100
804/804 [==============================] - 2s 2ms/step - loss: 4.6043 - accuracy: 0.2673
Epoch 32/100
804/804 [==============================] - 2s 2ms/step - loss: 4.6040 - accuracy: 0.2673
Epoch 33/100
804/804 [==============================] - 2s 2ms/step - loss: 4.6037 - accuracy: 0.2673
Epoch 34/100
804/804 [==============================] - 2s 2ms/step - loss: 4.6033 - accuracy: 0.2673
Epoch 35/100
804/804 [==============================] - 2s 3ms/step - loss: 4.6030 - accuracy: 0.2673
Epoch 36/100
804/804 [==============================] - 2s 3ms/step - loss: 4.6027 - accuracy: 0.2673
Epoch 37/100
804/804 [==============================] - 2s 3ms/step - loss: 4.6024 - accuracy: 0.2673
Epoch 38/100
804/804 [==============================] - 2s 2ms/step - loss: 4.6021 - accuracy: 0.2673
Epoch 39/100
804/804 [==============================] - 2s 2ms/step - loss: 4.6019 - accuracy: 0.2673
Epoch 40/100
804/804 [==============================] - 2s 2ms/step - loss: 4.6016 - accuracy: 0.2673
Epoch 41/100
804/804 [==============================] - 2s 2ms/step - loss: 4.6014 - accuracy: 0.2673
Epoch 42/100
804/804 [==============================] - 2s 2ms/step - loss: 4.6006 - accuracy: 0.2673
Epoch 43/100
804/804 [==============================] - 2s 3ms/step - loss: 4.5999 - accuracy: 0.2672
Epoch 44/100
804/804 [==============================] - 2s 3ms/step - loss: 4.5997 - accuracy: 0.2672
Epoch 45/100
804/804 [==============================] - 2s 3ms/step - loss: 4.5994 - accuracy: 0.2672
Epoch 46/100
804/804 [==============================] - 2s 2ms/step - loss: 4.5991 - accuracy: 0.2672
Epoch 47/100
804/804 [==============================] - 2s 2ms/step - loss: 4.5989 - accuracy: 0.2672
Epoch 48/100
804/804 [==============================] - 2s 2ms/step - loss: 4.5986 - accuracy: 0.2672
Epoch 49/100
804/804 [==============================] - 2s 3ms/step - loss: 4.5984 - accuracy: 0.2672
Epoch 50/100
804/804 [==============================] - 2s 2ms/step - loss: 4.5982 - accuracy: 0.2672
Epoch 51/100
804/804 [==============================] - 2s 2ms/step - loss: 4.5980 - accuracy: 0.2672
Epoch 52/100
804/804 [==============================] - 2s 2ms/step - loss: 4.5977 - accuracy: 0.2672
Epoch 53/100
804/804 [==============================] - 2s 2ms/step - loss: 4.5975 - accuracy: 0.2671
Epoch 54/100
804/804 [==============================] - 2s 2ms/step - loss: 4.5971 - accuracy: 0.2671
Epoch 55/100
804/804 [==============================] - 2s 2ms/step - loss: 4.5963 - accuracy: 0.2670
Epoch 56/100
804/804 [==============================] - 2s 2ms/step - loss: 4.5956 - accuracy: 0.2670
Epoch 57/100
804/804 [==============================] - 2s 2ms/step - loss: 4.5953 - accuracy: 0.2670
Epoch 58/100
804/804 [==============================] - 2s 2ms/step - loss: 4.5951 - accuracy: 0.2670
Epoch 59/100
804/804 [==============================] - 2s 2ms/step - loss: 4.5948 - accuracy: 0.2671
Epoch 60/100
804/804 [==============================] - 2s 2ms/step - loss: 4.5939 - accuracy: 0.2671
Epoch 61/100
804/804 [==============================] - 2s 2ms/step - loss: 4.5932 - accuracy: 0.2671
Epoch 62/100
804/804 [==============================] - 3s 3ms/step - loss: 4.5927 - accuracy: 0.2626
Epoch 63/100
804/804 [==============================] - 3s 3ms/step - loss: 4.5924 - accuracy: 0.2612
Epoch 64/100
804/804 [==============================] - 2s 2ms/step - loss: 4.5921 - accuracy: 0.2612
Epoch 65/100
804/804 [==============================] - 2s 3ms/step - loss: 4.5919 - accuracy: 0.2612
Epoch 66/100
804/804 [==============================] - 3s 3ms/step - loss: 4.5917 - accuracy: 0.2612
Epoch 67/100
804/804 [==============================] - 3s 4ms/step - loss: 4.5915 - accuracy: 0.2612
Epoch 68/100
804/804 [==============================] - 4s 6ms/step - loss: 4.5913 - accuracy: 0.2612
Epoch 69/100
804/804 [==============================] - 2s 3ms/step - loss: 4.5910 - accuracy: 0.2612
Epoch 70/100
804/804 [==============================] - 2s 2ms/step - loss: 4.5908 - accuracy: 0.2612
Epoch 71/100
804/804 [==============================] - 2s 3ms/step - loss: 4.5905 - accuracy: 0.2612
Epoch 72/100
804/804 [==============================] - 2s 2ms/step - loss: 4.5899 - accuracy: 0.2612
Epoch 73/100
804/804 [==============================] - 2s 3ms/step - loss: 4.5896 - accuracy: 0.2612
Epoch 74/100
804/804 [==============================] - 2s 2ms/step - loss: 4.5894 - accuracy: 0.2612
Epoch 75/100
804/804 [==============================] - 2s 2ms/step - loss: 4.5891 - accuracy: 0.2612
Epoch 76/100
804/804 [==============================] - 2s 2ms/step - loss: 4.5889 - accuracy: 0.2612
Epoch 77/100
804/804 [==============================] - 2s 3ms/step - loss: 4.5888 - accuracy: 0.2612
Epoch 78/100
804/804 [==============================] - 3s 4ms/step - loss: 4.5886 - accuracy: 0.2612
Epoch 79/100
804/804 [==============================] - 3s 3ms/step - loss: 4.5885 - accuracy: 0.2611
Epoch 80/100
804/804 [==============================] - 2s 3ms/step - loss: 4.5883 - accuracy: 0.2611
Epoch 81/100
804/804 [==============================] - 2s 3ms/step - loss: 4.5882 - accuracy: 0.2611
Epoch 82/100
804/804 [==============================] - 3s 3ms/step - loss: 4.5880 - accuracy: 0.2611
Epoch 83/100
804/804 [==============================] - 3s 4ms/step - loss: 4.5879 - accuracy: 0.2610
Epoch 84/100
804/804 [==============================] - 2s 3ms/step - loss: 4.5813 - accuracy: 0.2636
Epoch 85/100
804/804 [==============================] - 2s 2ms/step - loss: 4.5803 - accuracy: 0.2671
Epoch 86/100
804/804 [==============================] - 2s 3ms/step - loss: 4.5802 - accuracy: 0.2671
Epoch 87/100
804/804 [==============================] - 2s 3ms/step - loss: 4.5801 - accuracy: 0.2671
Epoch 88/100
804/804 [==============================] - 2s 3ms/step - loss: 4.5799 - accuracy: 0.2671
Epoch 89/100
804/804 [==============================] - 2s 2ms/step - loss: 4.5798 - accuracy: 0.2671
Epoch 90/100
804/804 [==============================] - 2s 2ms/step - loss: 4.5797 - accuracy: 0.2671
Epoch 91/100
804/804 [==============================] - 2s 2ms/step - loss: 4.5796 - accuracy: 0.2671
Epoch 92/100
804/804 [==============================] - 2s 2ms/step - loss: 4.5795 - accuracy: 0.2671
Epoch 93/100
804/804 [==============================] - 2s 2ms/step - loss: 4.5794 - accuracy: 0.2671
Epoch 94/100
804/804 [==============================] - 2s 2ms/step - loss: 4.5793 - accuracy: 0.2671
Epoch 95/100
804/804 [==============================] - 2s 2ms/step - loss: 4.5792 - accuracy: 0.2671
Epoch 96/100
804/804 [==============================] - 2s 2ms/step - loss: 4.5791 - accuracy: 0.2671
Epoch 97/100
804/804 [==============================] - 2s 3ms/step - loss: 4.5790 - accuracy: 0.2671
Epoch 98/100
804/804 [==============================] - 2s 2ms/step - loss: 4.5789 - accuracy: 0.2671
Epoch 99/100
804/804 [==============================] - 2s 2ms/step - loss: 4.5788 - accuracy: 0.2671
Epoch 100/100
804/804 [==============================] - 2s 2ms/step - loss: 4.5787 - accuracy: 0.2671

### Step 2: After finishing your models, display the accuracy scores achieved by each model, and compare the results.

In [ ]:
print("Original Model Results")

# Evaluate the model loss and accuracy metrics using the evaluate method and the test data
model_loss, model_accuracy = nn.evaluate(
    X_test_scaled, y_test, verbose=2
)

# Display the model loss and accuracy results
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

In [ ]:
print("Alternative Model 1 Results")

# Evaluate the model loss and accuracy metrics using the evaluate method and the test data

model_loss, model_accuracy = nn_A1.evaluate(
    X_test_scaled, y_test, verbose=2
)
# Display the model loss and accuracy results
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

In [ ]:
print("Alternative Model 2 Results")

# Evaluate the model loss and accuracy metrics using the evaluate method and the test data
model_loss, model_accuracy = nn_A2.evaluate(
    X_test_scaled, y_test, verbose=2
)

# Display the model loss and accuracy results
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

### Step 3: Save each of your alternative models as an HDF5 file.

In [ ]:
# Set the file path for the first alternative model
file_path = Path('../Starter_Code/AlphabetSoup_A1.h5')

# Export your model to a HDF5 file
nn_A1.save(file_path)

In [ ]:
# Set the file path for the second alternative model
file_path = Path('../Starter_Code/AlphabetSoup_A2.h5')

# Export your model to a HDF5 file
nn_A2.save(file_path)